#!/usr/bin/env bash
set -eu

mkdir cli
python3 -m venv .venv
PUSH_SCHEDULE_CONTENT=$(cat << EOF

import sys
import json

import redis

pool = redis.ConnectionPool(host='localhost', port=6379, db=0)
rd = redis.StrictRedis(connection_pool=pool)

for j in sys.argv[1:]:
    for task in json.loads(j):
        rd.rpush("schedule", json.dumps(task))
EOF
)
echo "$PUSH_SCHEDULE_CONTENT" > ./cli/push-schedule
sed -i "1i#!$(pwd)\\/.venv/bin/python" cli/push-schedule

GET_SCHEDULE_CONTENT=$(cat << EOF

import json

import redis
import tabulate

pool = redis.ConnectionPool(host='localhost', port=6379, db=0)
rd = redis.StrictRedis(connection_pool=pool)
omit = lambda s: s if len(s) < 65 else s[:62] + "..."

headers = ["parallel", "epoch", "settings"]
contents = [list(json.loads(content.decode("utf-8")).values()) for content in rd.lrange("schedule", 0, rd.llen("schedule"))]
contents = [[l[0], l[1], "\n".join([f"[{omit(config)}, {task}]" for config, task in l[2]])] for l in contents]
print(tabulate.tabulate(contents, headers, tablefmt="grid"))
EOF
)
echo "$GET_SCHEDULE_CONTENT" > ./cli/get-schedule
sed -i "1i#!$(pwd)\\/.venv/bin/python" cli/get-schedule

GET_MONITOR_CONTENT=$(cat << EOF

import json

import redis
import tabulate

pool = redis.ConnectionPool(host='localhost', port=6379, db=0)
rd = redis.StrictRedis(connection_pool=pool)
omit = lambda s: s if len(s) < 65 else s[:62] + "..."

headers = ["settings", "progress"]
contents = [[omit(k.decode("utf-8")), v.decode("utf-8")] for k, v in rd.hgetall("monitor").items()]
print(tabulate.tabulate(contents, headers, tablefmt="grid"))
EOF
)
echo "$GET_MONITOR_CONTENT" > ./cli/get-monitor
sed -i "1i#!$(pwd)\\/.venv/bin/python" cli/get-monitor

sudo chmod +x cli/push-schedule cli/get-schedule cli/get-monitor

source .venv/bin/activate
python -m pip install -U pip
python -m pip install redis tabulate