#!/usr/bin/env bash
set -eu

mkdir cli
python3 -m venv .venv
TEST=$(cat << EOF

import sys
import json

import redis

pool = redis.ConnectionPool(host='localhost', port=6379, db=0)
rd = redis.Redis(connection_pool=pool)

print(rd.get("sample").decode("utf-8"))
for j in sys.argv[1:]:
    for task in json.loads(j):
        rd.rpush("schedule", json.dumps(task))
EOF
)
echo "$TEST" > ./cli/push-schedule
sed -i "1i#!$(pwd)\\/.venv/bin/python" cli/push-schedule
sudo chmod +x cli/push-schedule

source .venv/bin/activate
python -m pip install -U pip
python -m pip install redis